find_program(ZIG_CC zigcc.sh REQUIRED)
find_program(ZIG_CXX zigcpp.sh REQUIRED)
find_program(ZIG_AR zigar.sh REQUIRED)
find_program(ZIG_RANLIB zigranlib.sh REQUIRED)
find_program(ZIG_RC zigrc.sh REQUIRED)

set(CMAKE_C_COMPILER "${ZIG_CC}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${ZIG_CXX}" CACHE FILEPATH "" FORCE)
set(CMAKE_AR "${ZIG_AR}" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${ZIG_RANLIB}" CACHE FILEPATH "" FORCE)
set(CMAKE_RC_COMPILER "${ZIG_RC}" CACHE FILEPATH "" FORCE)

